flowchart LR
    user([User])
    telegram(Telegram Bot)
    server([Server])
    logger([Logger])

    user -- 1 --> telegram
    telegram -- 2 / Auth --> server
    server -- 4 / Auth --> logger

    %% Server arrows as close to layout as possible
    server -- "bytes" --> server
    server -- "Auth" --> server
    server -- "Texts" --> server
    server -- "Mash" --> server
